version: '3.8'

services:
  frontend-and-nginx:
    # 前端打包 + 代理
    build:
      # 工程目录 zerorunner
      context: .
      dockerfile: zero-docker-file/Dockerfile-frontend-build
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
